### ISSUE TITLE
MoistThermodynamics compilation

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#82] opened 2019-02-23 14:29 UTC
`ERROR: LoadError: LoadError: LoadError: ArgumentError: Package CLIMAAtmosDycore does not have MoistThermodynamics in its dependencies:
- If you have CLIMAAtmosDycore checked out for development and have
  added MoistThermodynamics as a dependency but haven't updated your primary
  environment's manifest file, try Pkg.resolve().
- Otherwise you may need to report an issue with CLIMAAtmosDycore`

The use of 
```julia --project
]dev ../../Utilities
```
from src/ClimaAtmos/Dycore

solves it but creates the following:

`ERROR: LoadError: UndefVarError: LSRKmethods not defined`

as I execute 

`julia --project`

`julia> include("./drivers/rising_thermal_bubble.jl")`

(As a reference, MoistThermodynamics works correctly when used from Canary.)

**Comment by jkozdon** [comment] 2019-02-23 15:13
I cannot reproduce this problem working from the current CLIMA master:

```
jekozdon@Jeremys-MacBook-Pro:~/codes/CLIMA/src/ClimaAtmos/Dycore ± master
❯ julia --project
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.3 (2018-12-18)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(CLIMAAtmosDycore) pkg> dev ../../Utilities
 Resolving package versions...
  Updating `~/codes/CLIMA/src/ClimaAtmos/Dycore/Project.toml`
  [d528e2a8] + Utilities v0.0.0 [`../../Utilities`]
  Updating `~/codes/CLIMA/src/ClimaAtmos/Dycore/Manifest.toml`
  [f2b01f46] + Roots v0.7.4
  [d528e2a8] + Utilities v0.0.0 [`../../Utilities`]

(CLIMAAtmosDycore) pkg>
jekozdon@Jeremys-MacBook-Pro:~/codes/CLIMA/src/ClimaAtmos/Dycore ± ● master
❯ julia --project drivers/rising_thermal_bubble.jl
||Q||₂ (initial) =  2.4158256667836246e+08
-------------------------------------------------------------
doing VTK output =  vtk/RTB_2D_step0000
-------------------------------------------------------------
```

**Comment by smarras79** [comment] 2019-02-23 15:15
@jkozdon  do you have

'using MoistThermodynamics'

in VanillaAtmosDiscretizations.jl?

**Comment by jkozdon** [comment] 2019-02-23 15:20
I have `using Utilities.MoistThermodynamics`

I suggest encapsulating exactly what you are trying to do in a pull-request and we can look at it next week.

**Comment by jkozdon** [comment] 2019-02-23 15:41
Look at 02fda2f3468cbb0ac9ee0828386f2362f914e44b (my branch for_simone)

**Comment by jkozdon** [comment] 2019-02-23 16:23
No problem. Closing issue.

**Closed by jkozdon** 2019-02-23 16:23 UTC
